apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "chamelion.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.orchestrator.provider.auth.apiKey }}
  orchestrator-api-key: {{ .Values.orchestrator.provider.auth.apiKey | quote }}
  {{- end }}
  {{- if .Values.governance.enabled }}
  db-password: {{ .Values.database.password | quote }}
  {{- if eq .Values.database.type "mongodb" }}
  mongo-uri: {{ .Values.database.uri | quote }}
  {{- end }}
  {{- if or (eq .Values.database.type "mysql") (eq .Values.database.type "mariadb") }}
  db-root-password: {{ .Values.database.password | quote }}
  {{- end }}
  {{- end }}
  {{- range .Values.agents }}
  {{- if .provider.auth.apiKey }}
  agent-{{ .name }}-api-key: {{ .provider.auth.apiKey | quote }}
  {{- end }}
  {{- end }}
